"""
-> Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.

return the letter that was added to t.

"""

from collections import Counter

class Solution:
    def findDifference(self, s: str, t: str) -> str:
        count_s, count_t = Counter(s), Counter(t)

        for c in count_t:
            if c not in count_s:
                return c
            if count_s[c] < count_t[c]:
                return c
            
        